config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_up: 'register', sign_out: 'logout'}
  resources :portfolios, except: [:show]

  get 'portfolios/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'portfolios/angular', to: 'portfolios#angular'
  get 'portfolios/ruby_on_rails', to: 'portfolios#ruby_on_rails'

  root to: "pages#home"

  get 'about', to: 'pages#about'
  get 'websiteInfo', to: 'pages#websiteInfo'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
end

app/models/blog.rb
class Blog < ApplicationRecord
    enum status: {draft: 0, published: 1}
    extend FriendlyId
    friendly_id :title, use: :slugged

    validates_presence_of :title, :body

    belongs_to :topic
    belongs_to :user

    # Defines when Friendly_Id changes / updates the slug value
    # Here we have set it to change on change in title.
    # FriendlyId version 5(Rails 4 compatible) doesnt re-generates unless we define it explicitly
    def should_generate_new_friendly_id?
        title_changed?
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  access all: [:show, :index],
        user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]},
        editor: {except: [:destroy]},
        site_admin: :all
  layout "blog"

  # GET /blogs
  # GET /blogs.json
  def index
    # byebug

    blogs1 = Blog.where(:user_id=> current_user.id, :status=>0)
    blogs2 = Blog.where(:status=>1)
    unless blogs1.nil?
      @blogs = blogs1.page(params[:page]).per(5)
    end
    unless blogs2.nil?
      @blogs = @blogs + blogs2
    end
    @page_title = "Portfolio-Blogs | Blogs"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @page_title = "Portfolio-Blogs | " + @blog.title
    @seo_keywords = @blog.body
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params.merge(topic_id: 3, user_id: current_user.id))

    # byebug

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    # byebug
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
    redirect_to blogs_url, notice: 'Status has been updated'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper

    class CodeRayify < Redcarpet::Render::HTML
        def block_code(code, language)
            CodeRay.scan(code, language).div
        end
    end

    def markdown(text)
        codeRayified = CodeRayify.new(filter_html: true, hard_wrap: true)

        options = {
            fenced_code_blocs: true,
            no_intra_emphasis: true,
            autolink: true,
            lax_html_blocks: true,
            tables: true,
            strikethrough: true,
            underline: true,
            highlight: true,
            quote: true,
            superscript: true,
        }

        markdown_to_html = Redcarpet::Markdown.new(codeRayified, options)
        markdown_to_html.render(text).html_safe
    end
end

app/views/blogs/_blog.html.erb
<div class="blog-post">
  <h2 class="blog-post-title"><%= link_to blog.title, blog %></h2>
  <% portfolio_item = Portfolio.find_by(user_id: blog.user_id) %>
  <p class="blog-post-meta">Created <%= distance_of_time_in_words(blog.created_at, Time.now)%> ago, by <%= blog.user.first_name%></a></p>
  <p><%= markdown blog.body[0,50] %><%= link_to " ... more", blog %></p>
</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>
      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: 'form-control', rows: 15 %>
  </div>

  <div class='row'>
    <div class='col-md-4'>
      <div class="actions">
        <%= form.submit "Submit", class: 'btn btn-success btn-block'  %>
      </div>
    </div>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="col-md-8 blog-main blog-width">
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', @blog %>
</div>

app/views/blogs/index.html.erb
<div class="col-md-8 blog-main blog-width">
  <h3 class="pb-1 mb-4 font-italic border-bottom">
    Fresh from the World of Blogs ...
  </h3>

  <%# <%= render @blogs.where(status: "published")%>
  <%= render @blogs %>
  <%# <%= paginate @blogs %>
</div>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<div class="col-md-8 blog-main blog-width">
  <div class="blog-post">
    <h2 class="blog-post-title"><%= @blog.title %></h2>
    <% portfolio_item = Portfolio.find_by(user_id: @blog.user_id) %>
    <%# <p class="blog-post-meta">Created <%= distance_of_time_in_words(@blog.created_at, Time.now) ago, by <%= link_to  @blog.user.first_name, portfolio_path(portfolio_item.id) %>
    <p class="blog-post-meta" style="color: #820700">Created <%= distance_of_time_in_words(@blog.created_at, Time.now)%> ago, by <%= @blog.user.first_name%></p>

    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <%= link_to 'Home', root_path, class: "breadcrumb-item" %>
        <%= link_to 'Blogs', blogs_path, class: "breadcrumb-item" %>
        <li class="breadcrumb-item active" aria-current="page">Library</li>
      </ol>
    </nav>
    <p><%= link_to @blog.status, toggle_status_blog_path(@blog), class: "btn btn-sm btn-outline-success" if (logged_in?(:site_admin, :editor) && current_user.id==@blog.user.id) %>
       <%= link_to 'Edit', edit_blog_path(@blog), class: "btn btn-sm btn-outline-primary" if (logged_in?(:site_admin, :editor) && current_user.id==@blog.user.id)%>
       <%= link_to 'Delete', @blog, method: :delete, class: "btn btn-sm btn-outline-danger", data: { confirm: 'Are you sure?'} if logged_in?(:site_admin)%></p>
    <div class="card card-body" style="background-color: #ededed">
      <p><%= markdown(@blog.body) %></p>
    </div>

    <%= link_to 'Back', blogs_path %>
  </div>
</div>