config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_up: 'register', sign_out: 'logout'}
  resources :portfolios, except: [:show]

  get 'portfolios/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'portfolios/angular', to: 'portfolios#angular'
  get 'portfolios/ruby_on_rails', to: 'portfolios#ruby_on_rails'

  root to: "pages#home"

  get 'about', to: 'pages#about'
  get 'websiteInfo', to: 'pages#websiteInfo'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                  reject_if: lambda{ |attr| attr['name'].blank? }


  include Placeholder
  validates_presence_of :title, :subtitle, :body, :main_image, :thumb_image

  belongs_to :user

  def self.angular
    where(title: "Angular")
  end

  #lambda function
  scope :ruby_on_rails, -> {where(title: "Ruby on Rails")}

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: "350", width: "350")
    self.thumb_image ||= Placeholder.image_generator(height: "150", width: "150")
  end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  access all: [:show, :index],
        user: {except: [:destroy, :create, :update, :edit, :new]},
        editor: {except: [:destroy]},
        site_admin: :all
  layout "portfolio"
    def index
        @portfolio_items = Portfolio.all
    end

    def angular
        @angular_portfolio_items = Portfolio.angular
    end

    def ruby_on_rails
        @portfolio_ruby_on_rails = Portfolio.ruby_on_rails
    end

    def new
        @portfolio_item = Portfolio.new
    end

    def create
        @portfolio_item = Portfolio.new(portfolio_params.merge(user_id: current_user.id))
        if current_user.roles=="user"
          current_user.update(roles: "editor")
        end

        respond_to do |format|
          if @portfolio_item.save
            format.html { redirect_to portfolios_path, notice: 'portfolio_item was successfully created.' }
            format.json { render :show, status: :created, location: @blog }
          else
            format.html { render :new }
            format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
          end
        end
    end

    def edit
        @portfolio_item = Portfolio.find(params[:id])
    end

    def update
        @portfolio_item = Portfolio.find(params[:id])
        respond_to do |format|
          if @portfolio_item.update(portfolio_params)
            format.html { redirect_to portfolios_path, notice: 'portfolio_item was successfully updated.' }
            format.json { render :show, status: :ok, location: @portfolio_item }
          else
            format.html { render :edit }
            format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
          end
        end
    end

    def show
        @portfolio_item = Portfolio.find(params[:id])
    end

    def destroy
        @portfolio_item = Portfolio.find(params[:id])
        @portfolio_item.destroy

        respond_to do |format|
            format.html { redirect_to portfolios_url, notice: "Record was removed"}
        end
    end

private
    def portfolio_params
      params.require(:portfolio).permit(:title,
                                        :subtitle,
                                        :body,
                                        :facebook_link,
                                        :github_link,
                                        :linkedin_link,
                                        :github_link,
                                        :insta_link,
                                        :twitter_link,
                                        technologies_attributes: [:name]
                                        )
    end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |f|%>
  <% if portfolio_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(portfolio_item.errors.count, "error") %> prohibited this blog from being saved:</h2>
      <ul>
        <% portfolio_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='row'>
    <div class='col-md-6'>
      <div class="form-group">
          <%= f.label :title%>
          <%= f.text_field :title, class: 'form-control'%>
      </div>
      <div class="form-group">
          <%= f.label :subtitle%>
          <%= f.text_field :subtitle, class: 'form-control'%>
      </div>
      <hr>
      <div class="form-group">
          <%= f.label :"Facebook Link"%>
          <%= f.text_field :facebook_link, class: 'form-control'%>
      </div>
      <div class="form-group">
          <%= f.label :"Linkedin Link" %>
          <%= f.text_field :linkedin_link, class: 'form-control'%>
      </div>
      <div class="form-group">
          <%= f.label :"Instagram Link"%>
          <%= f.text_field :insta_link, class: 'form-control'%>
      </div>
      <div class="form-group">
          <%= f.label :"Github Link"%>
          <%= f.text_field :github_link, class: 'form-control'%>
      </div>
      <div class="form-group">
          <%= f.label :"Twitter Link"%>
          <%= f.text_field :twitter_link, class: 'form-control'%>
      </div>
    </div>
    <div class='col-md-6'>
      <div class="form-group">
          <%= f.label :body%>
          <%= f.text_area :body, class: 'form-control', rows: 23 %>
      </div>
    </div>
  </div>

  <div class='row'>
    <div class='col-md-6'>
    </div>
    <div class='col-md-6'>
      <div class="actions">
        <%= f.submit "Submit", class: 'btn btn-success btn-block'  %>
      </div>
    </div>
  </div>
<% end%>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-3">
  <div class="card mb-3 box-shadow" style="width: 100%; height: 90%">
    <%= image_tag "portfolio_basic_image.png", width: '100%' if !portfolio_item.thumb_image.nil?%>
    <div class="card-body" style="width: 90%; height: 90%">
      <p class="card-text"><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id)%></p>
      <p class="card-text"><%= portfolio_item.subtitle%></p>
      <p class="card-text">Name : <%= portfolio_item.user.first_name if !portfolio_item.user.nil? %></p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <%= link_to 'Edit', edit_portfolio_path(portfolio_item.id), class: "btn btn-sm btn-outline-success" if logged_in?(:site_admin)%>
          <%= link_to 'Delete', portfolio_item, method: :delete, class: "btn btn-sm btn-outline-danger", data: { confirm: 'Are you sure?'} if logged_in?(:site_admin)%>
        </div>
        <small class="text-muted"><%= distance_of_time_in_words(portfolio_item.created_at, Time.now)%> ago</small>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Item</h1>
<br>
<% @angular_portfolio_items.each do |portfolio_item|%>
    <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id)%></p>
    <p><%= portfolio_item.subtitle%></p>
    <p><%= portfolio_item.body%></p>
    <%= image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil?%>
    <%= link_to "Edit", edit_portfolio_path(portfolio_item.id) %>
    <%= link_to "Show", portfolio_show_path(portfolio_item.id)%>
    <td><%= link_to 'Destroy', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <br>
<% end %>

<%= link_to "Back to Index Page", portfolios_path%>

app/views/portfolios/edit.html.erb
<div class="container">
  <h1>Edit Portfolio</h1>
  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
        <%= render partial: 'portfolio_item', collection: @portfolio_items%>
    </div>
  </div>
  <!-- <a href=portfolios/new>Create New Item</a> -->
</div>

app/views/portfolios/new.html.erb
<div class="container">
  <h1>Create Your Portfolio</h1>
  <%= render 'form', portfolio_item: @portfolio_item%>
</div>

app/views/portfolios/ruby_on_rails.html.erb
<h1>Ruby on Rails Portfolio Item</h1>
<br>
<% @portfolio_ruby_on_rails.each do |portfolio_item|%>
    <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id)%></p>
    <p><%= portfolio_item.subtitle%></p>
    <p><%= portfolio_item.body%></p>
    <%= image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil?%>
    <%= link_to "Edit", edit_portfolio_path(portfolio_item.id) %>
    <%= link_to "Show", portfolio_show_path(portfolio_item.id)%>
    <td><%= link_to 'Destroy', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <br>
<% end %>

<%= link_to "Back to Index Page", portfolios_path%>

app/views/portfolios/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2">
      <%= image_tag "portfolio_basic_image.png" if !@portfolio_item.main_image.nil?%>
    </div>
    <div class="col-md-10">
      <h1><%= @portfolio_item.title%></h3>
      <h3><%= @portfolio_item.subtitle%></h5>
      <h5><%= @portfolio_item.user.name%></h1>
      <hr>
      <%= markdown @portfolio_item.body%>
      <hr>
      <div class="row">
        <div class="col-md-2">
          <%= link_to "  ", @portfolio_item.facebook_link , class: "fa fa-facebook social-links social-links" %>
        </div>
        <div class="col-md-2">
          <%= link_to "  ", @portfolio_item.insta_link , class: "fa fa-instagram social-links social-links" %>
        </div>
        <div class="col-md-2">
          <%= link_to "  ", @portfolio_item.linkedin_link , class: "fa fa-linkedin social-links social-links" %>
        </div>
        <div class="col-md-2">
          <%= link_to "  ", @portfolio_item.twitter_link , class: "fa fa-twitter social-links social-links" %>
        </div>
        <div class="col-md-2">
          <%= link_to "  ", @portfolio_item.github_link , class: "fa fa-github social-links social-links" %>
        </div>
      </div>
    </div>
  </div>
  <%= link_to "Back", portfolios_path%>
</div>