config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_up: 'register', sign_out: 'logout'}
  resources :portfolios, except: [:show]

  get 'portfolios/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'portfolios/angular', to: 'portfolios#angular'
  get 'portfolios/ruby_on_rails', to: 'portfolios#ruby_on_rails'

  root to: "pages#home"

  get 'about', to: 'pages#about'
  get 'websiteInfo', to: 'pages#websiteInfo'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p><%= copyright_generator%>
     | <%= link_to "About", about_path%> | <%= link_to "Website Info", websiteInfo_path%>
    </p>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Welcome, <%= current_user.first_name %></h3>
    <nav class="nav nav-masthead justify-content-center app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper('nav-link')%>
    </nav>
  </div>
</header>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p><%= copyright_generator%> | <%= link_to "About", about_path%> | <%= link_to "Website Info", websiteInfo_path%></p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_nav.html.erb
<header class="blog-header py-3">
  <div class="row flex-nowrap justify-content-between align-items-center">
    <div class="col-6">
      <a class="blog-header-logo text-dark" href="#">Welcome, <%= current_user.first_name %></a>
    </div>
    <div class="col-4 d-flex justify-content-end align-items-center">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper('btn btn-sm btn-light')%>
    </div>
  </div>
</header>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
  <%# <div class="p-3 mb-3 bg-light rounded">
    <h4 class="font-italic">About</h4>
    <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div> %>

  <%= link_to 'Create New Blog', new_blog_path, class: "btn btn-warning btn-block" if logged_in?(:site_admin, :editor) %>
  <div class="p-3">
  <div class="p-3">
    <h5><%= session_helper("blog") %></h5>
    <h5 class="font-italic">Wanna connect with me..? Visit my profile</h5>
    <ol class="list-unstyled">
      <li><a class="fa fa-github social-links" href="https://github.com/soumya74"></a></li>
      <li><a class="fa fa-instagram social-links" href="https://www.instagram.com/soumyasengupta74/"></a></li>
      <li><a class="fa fa-facebook social-links" href="https://www.facebook.com/soumya74"></a></li>
      <li><a class="fa fa-linkedin social-links" href="https://www.linkedin.com/in/soumya-s-4247a777/"></a></li>

    </ol>
  </div>
</aside><!-- /.blog-sidebar -->

app/views/shared/_nav.html.erb
<div class=<%= location %>>
  <div><%= link_to "Home", root_path%></div>
  <div><%= link_to "About", about_path%></div>
  <div><%= link_to "Website Info", websiteInfo_path%></div>
  <div><%= link_to "Blogs", blogs_path%></div>
  <div><%= link_to "Portfolios", portfolios_path%></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p><%= copyright_generator%> | <%= link_to "About", about_path%> | <%= link_to "Website Info", websiteInfo_path%></p>
    <p><%= session_helper("application") %></p>
  </div>
</footer>

app/views/shared/_portfolio_masterhead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Portfolio Power</h1>
    <p class="lead text-muted">Portfolios are great to showcase ones experience in a specific domain. Just explore through my portfolios for understanding my experience & expertise in each domain.</p>
    <p>
      <% if !current_user.is_a?(GuestUser) %>
        <% portfolio_item = Portfolio.find_by(user_id: current_user.id) %>
        <%= link_to "Add Another Portfolio", new_portfolio_path, class: "btn btn-success my-2" if (logged_in?(:site_admin, :editor)) %>
        <%= link_to "Start Writing Blog", new_blog_path, class: "btn btn-primary my-2" if !portfolio_item.nil? %>
        <%# <%= link_to "Edit your Portfolio", edit_portfolio_path(portfolio_item.id), class: "btn btn-secondary my-2" if (logged_in?(:site_admin, :editor) && !portfolio_item.nil?) %>
      <% end %>
      <%# <a href="#" class="btn btn-primary my-2">Start Writing a Blog</a> %>
      <%# <a href="#" class="btn btn-secondary my-2">Edit your Portfolio</a> %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<header>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="col-4 pt-1 container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <strong>Welcome, <%= current_user.first_name %></strong>
      </a>
    </div>
    <div class="col-4 text-center">
      <a class="blog-header-logo text-dark" href="#">Welcome, <%= current_user.first_name %></a>
    </div>
    <div class="col-4 d-flex justify-content-end align-items-center">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper('btn btn-outline-warning')%>
    </div>
  </div>
</header>

app/views/shared/_website_headline.html.erb
Soumya | SSG